/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package src;

import javax.swing.JOptionPane;
import static src.PruebaAdmonEmpleados.ae;

/**
 *
 * @author beelze
 */
public class FrmAltas extends javax.swing.JDialog {

    int clave;
    /**
     * Creates new form FrmAltas
     */
    public FrmAltas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpEmpleados = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        btnCapturar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rbtSupervisor = new javax.swing.JRadioButton();
        rbtObrero = new javax.swing.JRadioButton();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ALTA DE UN EMPLEADO");

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel1.setText("Clave del empleado:");

        btnCapturar.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnCapturar.setText("Capturar datos");
        btnCapturar.setEnabled(false);
        btnCapturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel2.setText("Tipo de empleado:");

        grpEmpleados.add(rbtSupervisor);
        rbtSupervisor.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        rbtSupervisor.setText("Supervisor");
        rbtSupervisor.setEnabled(false);

        grpEmpleados.add(rbtObrero);
        rbtObrero.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        rbtObrero.setSelected(true);
        rbtObrero.setText("Obrero");
        rbtObrero.setEnabled(false);
        rbtObrero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtObreroActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2)
                        .addComponent(btnCapturar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtObrero)
                            .addComponent(rbtSupervisor))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtSupervisor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtObrero)
                .addGap(18, 18, 18)
                .addComponent(btnCapturar)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbtObreroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtObreroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtObreroActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        clave = Integer.parseInt(txtClave.getText());
        if (ae.busqueda(clave) == -1) {
            rbtSupervisor.setEnabled(true);
            rbtObrero.setEnabled(true);
            btnCapturar.setEnabled(true);
        } else {
             JOptionPane.showMessageDialog(
                this, 
                "Ya existe un empleado con esa clave",
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarActionPerformed
       this.setVisible(false);
        if (rbtSupervisor.isSelected()) {
            new FrmAltasSupervisor(null, true, clave).setVisible(true);
        } else {
            new FrmAltasObrero(null, true, clave).setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnCapturarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCapturar;
    private javax.swing.ButtonGroup grpEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbtObrero;
    private javax.swing.JRadioButton rbtSupervisor;
    private javax.swing.JTextField txtClave;
    // End of variables declaration//GEN-END:variables
}
