/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author beelze
 */
public class PruebaAdmonEmpleados extends javax.swing.JFrame {

    public static AdmonEmpleados ae = new AdmonEmpleados();
    /**
     * Creates new form PruebaAdmonEmpleados
     */
    public PruebaAdmonEmpleados() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuSistema = new javax.swing.JMenu();
        opcAcercaDe = new javax.swing.JMenuItem();
        opcSalir = new javax.swing.JMenuItem();
        mnuEmpleados = new javax.swing.JMenu();
        opcAltas = new javax.swing.JMenuItem();
        opcConsInd = new javax.swing.JMenuItem();
        opcConsGral = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("METALURGIA DE OCCIDENTE - CONTROL DE EMPLEADOS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        mnuSistema.setText("Sistema");
        mnuSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSistemaActionPerformed(evt);
            }
        });

        opcAcercaDe.setText("Acerca de...");
        opcAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcAcercaDeActionPerformed(evt);
            }
        });
        mnuSistema.add(opcAcercaDe);

        opcSalir.setText("Salir");
        opcSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcSalirActionPerformed(evt);
            }
        });
        mnuSistema.add(opcSalir);

        jMenuBar1.add(mnuSistema);

        mnuEmpleados.setText("Empleados");

        opcAltas.setText("Altas");
        opcAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcAltasActionPerformed(evt);
            }
        });
        mnuEmpleados.add(opcAltas);

        opcConsInd.setText("Consula Indivdual");
        opcConsInd.setEnabled(false);
        opcConsInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcConsIndActionPerformed(evt);
            }
        });
        mnuEmpleados.add(opcConsInd);

        opcConsGral.setText("Consulta General");
        opcConsGral.setEnabled(false);
        opcConsGral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcConsGralActionPerformed(evt);
            }
        });
        mnuEmpleados.add(opcConsGral);

        jMenuBar1.add(mnuEmpleados);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSistemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSistemaActionPerformed

    private void opcSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcSalirActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_opcSalirActionPerformed

    private void opcAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcAcercaDeActionPerformed
        JOptionPane.showMessageDialog(
                this, 
                "Sistema: Metalurgia de Occidente - Control de Empleados\n" +
                        "Version 1.0\n" +
                        "Programador: Luis Gerardo Esteban Flores\n" +
                        "Fecha: Mayo del 2023", 
                "Acerca de...", 
                JOptionPane.INFORMATION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_opcAcercaDeActionPerformed

    private void opcAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcAltasActionPerformed
        if (ae.getCont() < 50) {
            new FrmAltas(this, true).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(
                this, 
                "La base de datos esta llena",
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_opcAltasActionPerformed

    private void opcConsIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcConsIndActionPerformed
        int clave;
        String claveTexto;
        
        claveTexto = JOptionPane.showInputDialog(
                this, 
                "Clave del empleado a consultar", 
                "Ingresar clave", 
                JOptionPane.QUESTION_MESSAGE);
        if (claveTexto != null) {
            clave = Integer.parseInt(claveTexto);
            int celda = ae.busqueda(clave);
            if (celda != -1) {
                if (ae.getEmpleado(celda) instanceof Supervisor) {
                    new FrmConsIndSupervisor(this, true, celda).setVisible(true);
                } else {
                    new FrmConsIndObrero(this, true, celda).setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(
                this, 
                "No existe ningun empleado con esa clave",
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            }
        } 
    }//GEN-LAST:event_opcConsIndActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (ae.getCont() > 0) {
            opcConsInd.setEnabled(true);
            opcConsGral.setEnabled(true);
        }
    }//GEN-LAST:event_formWindowActivated

    private void opcConsGralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcConsGralActionPerformed
        new FrmConsGral(this, true).setVisible(true);
    }//GEN-LAST:event_opcConsGralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaAdmonEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaAdmonEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaAdmonEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaAdmonEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaAdmonEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuEmpleados;
    private javax.swing.JMenu mnuSistema;
    private javax.swing.JMenuItem opcAcercaDe;
    private javax.swing.JMenuItem opcAltas;
    private javax.swing.JMenuItem opcConsGral;
    private javax.swing.JMenuItem opcConsInd;
    private javax.swing.JMenuItem opcSalir;
    // End of variables declaration//GEN-END:variables
}
